name: Deploy Preview to GitHub Pages

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: erlef/setup-beam@v1.24.0
        with:
          otp-version: "28"
          gleam-version: "1.16.0"
          rebar3-version: "3"

      - uses: oven-sh/setup-bun@v2.2.0

      - run: gleam deps download

      - run: bun install

      - run: bun run vite build --base /saola/

      - uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v5.0.0
        id: deployment
